name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Pull docker image
      run: sudo docker pull aishitdharwal/cicd-praneeth:latest
    - name: Delete old container if exists
      run: sudo docker rm -f cicd-praneeth-container || true
    - name: Run new container
      run: sudo docker run -d -p 8000:1234 --name cicd-praneeth-container aishitdharwal/cicd-praneeth:latest
